### ISSUE TITLE
Air & Space Smithsonian

### ISSUE THREAD

**Issue by kizzjay1** [MetalChris/repository.metalchris#6] opened 2017-07-18 05:56 UTC
Hi! I love your repo but I'm having trouble with the Air & Space Smithsonian addon. It hasn't been playing the links for a few weeks now. I've tried clearing my cache & even rebooted my router to see if that was the issue. Would you please check into it? If everything looks good on your end, do you have any other ideas of what I can do to get the links to play? Thank you!

**Comment by MetalChris** [comment] 2017-07-18 21:27
Thanks for bringing this to my attention.  It looks like they've made some changes to the website.  Give me a day or two and I should have a working version available.

**Comment by kizzjay1** [comment] 2017-07-19 00:12
I are so awesome! Thanks hun!

**Comment by MetalChris** [comment] 2017-07-20 21:45
Just uploaded version 0.0.5 which should fix the issues caused by the recent website changes.  Let me know if it works for you.  If it does, then I can close the issue.  If it doesn't, well then I have more work to do...

**Comment by kizzjay1** [comment] 2017-07-20 21:56
Yes, it works perfectly! Thank u for taking care of that so quickly!

**Comment by kizzjay1** [comment] 2017-07-21 21:10
sorry to bother you again! i was wondering if i could request an addon or make an addon suggestion? Huball just stopped maintaining the Pac-12 addon but i LOVED it & used it all the time. i know that other addons have it available but i prefer it to be a stand alone addon. if you have time, would you consider creating an addon for it? please?????

**Comment by MetalChris** [comment] 2017-07-22 12:16
I've got more than enough to keep me busy right now.  Since Air and Space is working again, I'm closing the issue.  Feel free to open a new one if it, or any of my other add-ons stop working.

**Closed by MetalChris** 2017-07-22 12:16 UTC
