### ISSUE TITLE
The CW

### ISSUE THREAD

**Issue by Arkadia2008** [MetalChris/repository.metalchris#37] opened 2018-09-17 12:57 UTC
Still not working for me with v.0.0.3. Tested on Windows and Android with Krypton and Leia.

[]https://paste.kodi.tv/umolerovug

**Comment by MetalChris** [comment] 2018-09-17 23:06
I can see where it is failing in the log you've provided, but I'm unable to reproduce the error on either windows or Android.  Are you by chance outside the US?

**Comment by Arkadia2008** [comment] 2018-09-18 07:42
Yes I am, but The CW works fine for me in browser and Android app using a Smart DNS.

Is your addon scraping the iOS mobile app for data?

**Comment by MetalChris** [comment] 2018-09-18 23:06
If you're using Smart DNS with your browser and Android app, why not use it with Kodi?  The add-on was not, and is not designed to circumvent geo-restrictions.  Unfortunately, the issue you are experiencing is due to your location, and not caused by a malfunction of the add-on.  As much as I'd like to help, it's really out of my hands, so I'm going to close this one.  Sorry.

**Closed by MetalChris** 2018-09-18 23:06 UTC
