### ISSUE TITLE
plugin.video.discovery-channels Not Working

### ISSUE THREAD

**Issue by pclabpro** [MetalChris/repository.metalchris#40] opened 2018-10-29 19:18 UTC
Installed on fresh build of Leia Beta 4 and not working.

**Comment by MetalChris** [comment] 2018-10-29 22:19
The content is region blocked for the U.S. only, so if you're anywhere else, it won't work.  If you're inside the U.S., you'll need to provide an unedited debug log for me to look at, since it is working fine for me on Krypton, and "not working" is not a good enough problem description (and also not surprising when you are using a beta version of software).

**Comment by pclabpro** [comment] 2018-11-02 00:43
Link to log is below,
Yes I'm in U.S., here is a fresh log with only launching the plugin for discovery.
When I try to launch a channel I get "Discovery Error, see log for more details"

The end of the log seems to have some warnings about:
20:13:14.042 T:493530277104 WARNING: CAddonSettings[plugin.video.discovery-channels]: failed to parse enable condition "!eq(3,false)" of old setting definition for "parser"
20:13:14.042 T:493530277104 WARNING: CAddonSettings[plugin.video.discovery-channels]: cannot reference setting (relative index: 3; absolute index: 6) in another category in old setting condition "!eq(3,false)" for "player"

Then it throws an IO exception
[kodi.log](https://github.com/MetalChris/repository.metalchris/files/2540618/kodi.log)

**Comment by MetalChris** [comment] 2018-11-02 21:46
Sorry, I should've noticed the word 'build' in your first post.  I can see from the log that you have at least a half dozen banned add-ons installed too.  This makes it way too difficult to diagnose what may be going on in your situation.  I've never seen the specific errors you've posted above, but the IO exception indicates the required cookie file does not exist.  The add-on should be saving the cookie file, but you may have some read/write permission issues going on that are preventing it from doing so, and this would not be caused by the add-on.  This may also be the reason I'm seeing similar 'failed to parse' errors in the log regarding other add-ons you have installed.  I'd suggest completely removing your 'build', and then installing an official version of Kodi Krypton from kodi.tv/download, then install the add-on and try again.  If the errors continue, post a link to a full, unedited log without any banned add-ons and I'll take another look.  Until then, since this does not appear to be add-on related, I'm going to close this issue.

**Closed by MetalChris** 2018-11-02 21:46 UTC

**Comment by pclabpro** [comment] 2018-11-04 18:17
MetalChris, that is fair.  As a Java and C++ coder myself I understand that other addons with poor written code can cause issues.  I also wasn't clear using the word "build".  I had downloaded the package from kodi.tv and installed addons myself, not from someone else's "build".

I have two platforms to troubleshoot on, the first being RPI3 running LibreElec, and the other is MX-10 running Android Oreo.

On RPI3 with Kodi Leia Beta 4 clean install I get the same error. (Log available upon request).

Then today I tested on the MX-10, with Kodi Leia Beta 4 & 5 clean install, and dropped back to Kodi Krypton 17.6 clean install and the same issue persists on this box.  Attached are 17.6 and 18b4 logs.

Also, I can confirm that the cookies.lwp file does not exist in that directory where the exception was thrown.

Then the error getting Directory for the URL.  I noticed that discoverygo now redirects to the main website.  I'm not sure if this was always the case, or if this is something new causing issues.

Let me know how I can help ;)
[kodiLeiaBeta4.log](https://github.com/MetalChris/repository.metalchris/files/2546132/kodiLeiaBeta4.log)
[kodiKrypton17_6.log](https://github.com/MetalChris/repository.metalchris/files/2546133/kodiKrypton17_6.log)



I do have some nicer logs to show you this time, they are untouched, I just renamed them.
